name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        optimize: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Build
        run: zig build -Doptimize=${{ matrix.optimize }}
