name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64-linux-gnu, wasm32-freestanding-musl]
        optimize: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.10
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Build
        run: |
          zig build -Doptimize=${{ matrix.optimize }} -Dtarget=${{ matrix.target }} -freference-trace -fsummary
